### ISSUE TITLE
Cant enrich layer

### ISSUE THREAD

**Issue by driskull** [Esri/impact-summary-map-template-js#102]
http://services.arcgis.com/Wl7Y1m92PbjtJs5n/arcgis/rest/services/NikeDecimalLayer/FeatureServer/0

I'm unable to enrich or configure this layer. It says it doesnt have numeric data, but it does.

![screen shot 2015-02-24 at 1 21 21 pm](https://cloud.githubusercontent.com/assets/1231455/6359444/182eef2c-bc28-11e4-91cb-555c2093ff80.png)
![screen shot 2015-02-24 at 1 21 15 pm](https://cloud.githubusercontent.com/assets/1231455/6359445/197ba5fa-bc28-11e4-883a-9cc7119ab629.png)

I try to uncheck the checkbox but nothing happens.

**Comment by driskull** [comment]
This may not be an issue. I'm only seeing it on our QA environment so hold off on any action.

**Comment by driskull** [comment]
@CTDisasterManagement do you know why this may be failing on an organization? It lets me select the layer but not enrich or uncheck the checkbox.

**Comment by CTDisasterManagement** [comment]
@driskull We tried to reproduce the issue but were unable to do so. Please see the link below with the same layer.

http://203.199.47.152/LimNextGen/ism/?appid=750a3d38e8574f8bb7ebacfa986263ed&edit=t

username - bisen123
password - bisen123

Please let us know if we are missing anything here.

Thanks!

**Comment by driskull** [comment]
Thanks for testing. It might be something with the org or geoenrichment. Do you know of any reasons why that message would show up when the layer is valid?

**Comment by CTDisasterManagement** [comment]
We will look into this in detail and keep you posted.

**Comment by driskull** [comment]
Ok thanks. The enrichment isnt working on our QA site but it is working on our Dev site. We're not sure of the difference or if its something with the organization. Let us know what might be causing the failure.

**Comment by iwittenmyer** [comment]
@CTDisasterManagement  do you have credentials to test it on QA?

**Comment by driskull** [comment]
I put the credentials on basecamp for them.

**Comment by CTDisasterManagement** [comment]
@driskull We tested the links provided and observed that there is change in environment and host URL. We are investigating the issue and will keep you posted.

**Comment by CTDisasterManagement** [comment]
@driskull 
Due to difference in the portal, we have to change the portal URL in the application which is configurable (i.e. “sharingHost” in the config file, which by default is set to www.arcgis.com )
 
We are creating an object “serverInfo” in dataBrowser.html file were we are initializing different parameters like Server URL, Token Service URL and so on (to avoid Identity Manager on opening Data Browser window). We also need to change these URL’s accordingly.
Example - for portal - http://hawaiian-org.mapsqa.arcgis.com/ we have to set Token Service URL as - https://geoenrichqa.arcgis.com/ArcGIS/tokens
 
We did these changes and found that Data Browser widget is not working as expected on different portals other than arcgis.com. Identity manager appears and when we try to sign in with any organization account (other than arcgis.com), it shows error message as “username or password you entered is incorrect”.
 
We will investigate this further.

**Comment by driskull** [comment]
@CTDisasterManagement the sharinghost gets set up by the template.js. It should be used after the template is ready.

All urls for portals should be built using this url. The identity manager will use the sharinghost url.

You shouldn't have to set anything, just use the "sharinghost" url with identiymanager. Seems like dataBrowser just needs to use template.js

**Comment by CTDisasterManagement** [comment]
@driskull 
Yes, we are using sharing host to build all the portal URLs now. 

We further investigated the issue and observed that:

Url for Geoenrichment is configured in Geoenrichment/config.js file, where portalUrl, Url for server and
locatorUrl are hardcoded.

However there is one more file (“tasks/geoenrichment/GeoenrichmentTask.js”) where Geoenrichment URL is hardcoded.

So this seems to be an Geoenrichment widget’s problem, where they are pointing to arcgis online Geoenrichment service.

You will find hardcoded URLs in these two js files :

1.	http://js.arcgis.com/3.13/esri/tasks/geoenrichment/GeoenrichmentTask.js 

2.	http://js.arcgis.com/3.13/esri/dijit/geoenrichment/config.js

Please let us know if you would like us to overwrite the widget and fix this issue.

Thanks!
