### ISSUE TITLE
Issue with >1,000 polygons? 

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/impact-summary-map-template-js#111]
@driskull Can you check out this app? http://www.arcgis.com/apps/ImpactSummary/index.html?appid=ce890faad47e49f98df71ee9e0afd798

It keeps defaulting to zooming to the upper right most polygon and I have no idea why? 
![image](https://cloud.githubusercontent.com/assets/4256979/18376617/cff6ec66-76b4-11e6-8834-1c441d91c894.png)

Also - when I choose entire area - it numerically adds up to the right numbers - but only highlights the upper left most polygons? 
![image](https://cloud.githubusercontent.com/assets/4256979/18376581/8b97b244-76b4-11e6-84a7-9c104b931bea.png)

**Comment by driskull** [comment]
hey @pjdohertygis try setting the option "selectEntireAreaOnStart" to true. It should be in the builder.

**Comment by pjdohertygis** [comment]
@driskull when I try that setting it defaults to opening and zooming in on only the top left corner (and not all polygons are selected, although the numbers are representative of the entire area). 

![image](https://cloud.githubusercontent.com/assets/4256979/18421314/cb4ca740-78db-11e6-98f8-3d50930d6d94.png)

Here is the feature service if you would like to test. 
http://www.arcgis.com/home/item.html?id=9eb299b1c752401aa6cffcb0b20e8c33 

I have tried recreating the app and can replicate the issue.

**Comment by driskull** [comment]
hey @pjdohertygis looks like it wasnt able to select it because it exceeded the transfer limit.

[url](http://services3.arcgis.com/UJlXKlDHq85VvxWm/arcgis/rest/services/Tangaroa_Impact_Summary_Publish_v2/FeatureServer/2/query?f=json&where=1%20%3D%201&returnGeometry=true&spatialRel=esriSpatialRelIntersects&outFields=*&outSR=2193&quantizationParameters=%7B%22mode%22%3A%22view%22%2C%22originPosition%22%3A%22upperLeft%22%2C%22tolerance%22%3A1.0583354500042323%2C%22extent%22%3A%7B%22type%22%3A%22extent%22%2C%22xmin%22%3A1857648.0001%2C%22ymin%22%3A5781136.0001%2C%22xmax%22%3A2041384.0001%2C%22ymax%22%3A5858592%2C%22spatialReference%22%3A%7B%22wkid%22%3A2193%2C%22latestWkid%22%3A2193%7D%7D%7D)

**Comment by pjdohertygis** [comment]
Ah ok - so then is the only short-term solution to cut down the # of polygons? @driskull

**Comment by driskull** [comment]
I think so. Or maybe the complexity of them.
