### ISSUE TITLE
'Cancel' button saves the changes in Data Browser widget.

### ISSUE THREAD

**Issue by CTDisasterManagement** [Esri/impact-summary-map-template-js#82]
In AGOL Data Browser widget, currently Cancel also saves the changes.

Since we only have Cancel button on Home page of Data Browser, if User makes any changes in the Cart (top right), there is no way to save those changes. We need a way to have Apply button on home screen to save changes.

**Comment by driskull** [comment]
The issue is that the apply button is not showing when you are brought into the data browser with variables already set and then you remove one from the cart. We are using whats on jsdev.arcgis.com/3.12. We launch the browser with some variables set and if a user removes one of them the apply button isn’t showing.

**Comment by driskull** [comment]
@CTDisasterManagement this is still an issue, correct?

**Comment by CTDisasterManagement** [comment]
@driskull Yes it is.
